name: Publish Docker image

on:
  pull_request_target:
    types:
      - closed

  workflow_dispatch:


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata-portal
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: apsiminitiative/postats-portal
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile
          push: true
          target: postats-portal
          tags: ${{ steps.metadata-portal.outputs.tags }}
          labels: ${{ steps.metadata-portal.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata-collector
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: apsiminitiative/postats-collector
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile
          push: true
          target: postats-collector
          tags: ${{ steps.metadata-collector.outputs.tags }}
          labels: ${{ steps.metadata-collector.outputs.labels }}
